---
- name: create multiple users to all nodes
  hosts: webservers
  become: true
  tasks:
    - name: create  multiple users
      user: name='{{item}}' state=present
      with_items:
        - Ram
        - Lakshman
        - Bharat
