---
- name: install multiple packages to all nodes
  hosts: webservers
  become: true
  tasks:
    - name: install multiple packages
      yum:
        name: ['git','tree','java']
        state: installed
