---
- name: install multiple packages to all nodes
  hosts: webservers
  become: true
  tasks:
    - name: install multiple packages
      yum: name='{{item}}' state=present
      with_items:
        - git
        - tree
        - java
